baseURL = 'https://devot.netlify.app/'
languageCode = 'en-us'
title = 'DevOT blog'

theme = 'devot'

googleAnalytics = 'G-48E9108RES'

defaultContentLanguage = 'vn'

pygmentsUseClasses = true

[author]
    name = "Nguyễn Hoàng Nam"

[outputFormats]
    [outputFormats.RSS]
        mediaType = "application/rss+xml"
        baseName = "feed"

[menu]
    [[menu.main]]
        name = "Posts"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            autoHeadingID = true
            autoHeadingIDType = 'github'
            [markup.goldmark.parser.attribute]
                block = false
                title = true
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = false
            xhtml = false
        [markup.highlight]
            codeFences = true
            guessSyntax = true
            hl_Lines = ""
            lineNoStart = 1
            lineNos = false
            lineNumbersInTable = false
            tabWidth = 4
            noClasses = false

[languages]
    [languages.vn]
        languageName = 'vn'
    [languages.en]
        languageName = 'en'

[params]
    description = "The place where I share my Dev life and all about technical things I know"
    keywords = "Developer, Microservice, Machine Learning"
    twitterUsername = "@nguyenh79185323"
    socialImage = "/images/cover.jpeg"
