baseURL = ''
languageCode = 'en-us'
title = 'DevOT blog'

theme = 'devot'

googleAnalytics = 'G-48E9108RES'

[menu]
    [[menu.main]]
        name = "Posts"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            autoHeadingID = true
            autoHeadingIDType = 'github'
            [markup.goldmark.parser.attribute]
                block = false
                title = true
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = false
            xhtml = false
    [markup.highlight]
        style = 'github'
